[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
bytecode_hash = "none"
ignored_error_codes = [5574]  # Allow version pragma mismatch

[profile.token]
src = "src/token"
test = "test/token"
script = "script/token"
out = "out/token"
libs = ["lib"]
solc = "0.8.28"
bytecode_hash = "none"

[rpc_endpoints]
base_goerli = "https://goerli.base.org"
sepolia = "https://rpc.ankr.com/eth_sepolia"
